# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=128)),
                ('collection_file', models.FileField(upload_to='')),
                ('collection_hash', models.CharField(max_length=16)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_name', models.CharField(max_length=32)),
                ('motif', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=256)),
                ('sequence', models.CharField(max_length=4096)),
                ('collection_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_analysis_tool.Collection')),
            ],
        ),
    ]
